### PR TITLE
Fix broken WebSocket defragmentation

### LINKED ISSUE #382: Websocket multipart message does not work as expected
### Platform

ESP8266

### IDE / Tooling

PlatformIO

### What happened?

I tried to send from the browser a json file (size about 1k) via web socket to the module.
I installed a new environment to avoid side effects and I used the code from the exsample folder: "WebSocket.ino"

The code is working with single frames and works as expected...
Then I inserted the code from https://github.com/ESP32Async/ESPAsyncWebServer/wiki#async-websocket-event to get also the
multipart message to receive the large messages.

- The first message is received as expected... but with final set to true (!)
- The second message will also be received.. also with final set to true and index set to 0, the data pointer contains garbage
Output is (i inserted framelen with the parameter len to visualize it):

```
Connected clients: 1 / 1 total
index: 0, len: 1447, final: 1, opcode: 1, framelen: 528
ws[/ws][4] frame[0] text[0 - 4]: ws[/ws][5] text-message start
ws[/ws][5] frame[0] start[1447]
{     "logToSerial": true,     "traceMode": false,     "devicename": "LSC-device",     "devicepwd": "admin-geheim",     "autorestart": "86400",          "wifi": {         "ap_channel": 3,         "ap_hide": false,         "bssid": "aa:bb:33:22:11:fe",         "ap_ssid": "LSC-8eaa2c44",         "ap_mode": "0",         "dhcp": true,         "fallback": false,         "ssid": "WiFiOnICE",         "wifi_pwd": "JoJoBaOel",         "hostname": "LSC-Device"        },     "dewswitch": {         "dewdelta": 5.2,         "hysteresis
index: 0, len: 1447, final: 1, opcode: 1, framelen: 532
ws[/ws][5] frame[0] text[0 - 528]: ws[/ws][5] text-message start
ws[/ws][5] frame[0] start[1447]



index: 0, len: 1447, final: 1, opcode: 1, framelen: 379
ws[/ws][5] frame[0] text[0 - 532]: ws[/ws][5] text-message start
ws[/ws][5] frame[0] start[1447]
VSM
Connected clients: 1 / 1 total
```

- the next click with data "dd" produces:
```
ndex: 0, len: 1447, final: 1, opcode: 1, framelen: 4
ws[/ws][5] frame[0] text[0 - 379]: ws[/ws][5] text-message start
ws[/ws][5] frame[0] start[1447]
��dd
```
- here the data is corrupted...

I'm using 
- a D1 mini (ESP8266)
- PlatformIO
- Visual Code
- MacOS (M4) 26.2 (25C56)
- Using this libraries:
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESPAsyncTCP @ 2.0.0
|-- ESPAsyncWebServer @ 3.9.6
Building in debug mode

Thanks

Peter

### Stack Trace

No Stack Trace, cause the application did not crash..

### Minimal Reproductible Example (MRE)

Source code:

```
// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright 2016-2026 Hristo Gochkov, Mathieu Carbou, Emil Muratov, Will Miles

//
// WebSocket example
//

#include <Arduino.h>
#if defined(ESP32) || defined(LIBRETINY)
#include <AsyncTCP.h>
#include <WiFi.h>
#elif defined(ESP8266)
#include <ESP8266WiFi.h>
#include <ESPAsyncTCP.h>
#elif defined(TARGET_RP2040) || defined(TARGET_RP2350) || defined(PICO_RP2040) || defined(PICO_RP2350)
#include <RPAsyncTCP.h>
#include <WiFi.h>
#endif

#include <ESPAsyncWebServer.h>

static const char *htmlContent PROGMEM = R"(
<!DOCTYPE html>
<html>
<head>
  <title>WebSocket</title>
</head>
<body>
  <h1>WebSocket Example</h1>
  <p>Open your browser console!</p>
  <input type="text" id="message" placeholder="Type a message">
  <button onclick='sendMessage()'>Send</button>
  <script>
    var ws = new WebSocket('ws://192.168.4.1/ws');
    ws.onopen = function() {
      console.log("WebSocket connected");
    };
    ws.onmessage = function(event) {
      console.log("WebSocket message: " + event.data);
    };
    ws.onclose = function() {
      console.log("WebSocket closed");
    };
    ws.onerror = function(error) {
      console.log("WebSocket error: " + error);
    };
    function sendMessage() {
      var message = document.getElementById("message").value;
      ws.send(message);
      console.log("WebSocket sent: " + message);
    }
  </script>
</body>
</html>
  )";
static const size_t htmlContentLength = strlen_P(htmlContent);

static AsyncWebServer server(80);
static AsyncWebSocket ws("/ws");

void setup() {
  Serial.begin(115200);

#if ASYNCWEBSERVER_WIFI_SUPPORTED
  WiFi.mode(WIFI_AP);
  WiFi.softAP("esp-captive");
#endif

  // serves root html page
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/html", (const uint8_t *)htmlContent, htmlContentLength);
  });

  //
  // Run in terminal 1: websocat ws://192.168.4.1/ws => should stream data
  // Run in terminal 2: websocat ws://192.168.4.1/ws => should stream data
  // Run in terminal 3: websocat ws://192.168.4.1/ws => should fail:
  //
  // To send a message to the WebSocket server:
  //
  // echo "Hello!" | websocat ws://192.168.4.1/ws
  //
  ws.onEvent([](AsyncWebSocket *server, AsyncWebSocketClient *client, AwsEventType type, void *arg, uint8_t *data, size_t len) {
    (void)len;

    if (type == WS_EVT_CONNECT) {
      ws.textAll("new client connected");
      Serial.println("ws connect");
      client->setCloseClientOnQueueFull(false);
      client->ping();

    } else if (type == WS_EVT_DISCONNECT) {
      ws.textAll("client disconnected");
      Serial.println("ws disconnect");

    } else if (type == WS_EVT_ERROR) {
      Serial.println("ws error");

    } else if (type == WS_EVT_PONG) {
      Serial.println("ws pong");

    } else if (type == WS_EVT_DATA) {
      AwsFrameInfo *info = (AwsFrameInfo *)arg;
      Serial.printf("index: %" PRIu64 ", len: %" PRIu64 ", final: %" PRIu8 ", opcode: %" PRIu8 ", framelen: %d\n", 
        info->index, 
        info->len, 
        info->final, 
        info->opcode,
        len
    );
      String msg = "";
      if (info->final && info->index == 0 && info->len == len) {
        if (info->opcode == WS_TEXT) {
          data[len] = 0;
          Serial.printf("ws text: %s\n", (char *)data);
          client->ping();
        }
      } else {
        if(info->index == 0){
        if(info->num == 0)
          os_printf("ws[%s][%u] %s-message start\n", server->url(), client->id(), (info->message_opcode == WS_TEXT)?"text":"binary");
        os_printf("ws[%s][%u] frame[%u] start[%llu]\n", server->url(), client->id(), info->num, info->len);
      }

      os_printf("ws[%s][%u] frame[%u] %s[%llu - %llu]: ", server->url(), client->id(), info->num, (info->message_opcode == WS_TEXT)?"text":"binary", info->index, info->index + len);
      if(info->message_opcode == WS_TEXT){
        data[len] = 0;
        os_printf("%s\n", (char*)data);
      } else {
        for(size_t i=0; i < len; i++){
          os_printf("%02x ", data[I]);
        }
        os_printf("\n");
      }

      if((info->index + len) == info->len){
        os_printf("ws[%s][%u] frame[%u] end[%llu]\n", server->url(), client->id(), info->num, info->len);
        if(info->final){
          os_printf("ws[%s][%u] %s-message end\n", server->url(), client->id(), (info->message_opcode == WS_TEXT)?"text":"binary");
          if(info->message_opcode == WS_TEXT)
            client->text("I got your text message");
          else
            client->binary("I got your binary message");
        }
      }
      }
    }
  });

  // shows how to prevent a third WS client to connect
  server.addHandler(&ws).addMiddleware([](AsyncWebServerRequest *request, ArMiddlewareNext next) {
    // ws.count() is the current count of WS clients: this one is trying to upgrade its HTTP connection
    if (ws.count() > 1) {
      // if we have 2 clients or more, prevent the next one to connect
      request->send(503, "text/plain", "Server is busy");
    } else {
      // process next middleware and at the end the handler
      next();
    }
  });

  server.addHandler(&ws);

  server.begin();
}

static uint32_t lastWS = 0;
static uint32_t deltaWS = 100;

static uint32_t lastHeap = 0;

void loop() {
  uint32_t now = millis();

  if (now - lastWS >= deltaWS) {
    ws.printfAll("kp%.4f", (10.0 / 3.0));
    lastWS = millis();
  }

  if (now - lastHeap >= 2000) {
    Serial.printf("Connected clients: %u / %u total\n", ws.count(), ws.getClients().size());

    // this can be called to also set a soft limit on the number of connected clients
    ws.cleanupClients(2);  // no more than 2 clients

#ifdef ESP32
    Serial.printf("Free heap: %" PRIu32 "\n", ESP.getFreeHeap());
#endif
    lastHeap = now;
  }
}
```

Test data:
```
{
    "logToSerial": true,
    "traceMode": false,
    "devicename": "LSC-device",
    "devicepwd": "admin-geheim",
    "autorestart": "86400",
    
    "wifi": {
        "ap_channel": 3,
        "ap_hide": false,
        "bssid": "aa:bb:33:22:11:fe",
        "ap_ssid": "LSC-8eaa2c44",
        "ap_mode": "0",
        "dhcp": true,
        "fallback": false,
        "ssid": "WiFiOnICE",
        "wifi_pwd": "JoJoBaOel",
        "hostname": "LSC-Device"   
    },
    "dewswitch": {
        "dewdelta": 5.2,
        "hysteresis": 1.5,
        "min_outdoor": -10.3,
        "min_indoor": 10.1
    },
    "sensor": {
        "adjust_humidity": 5,
        "adjust_temp": -0.2,
        "physical": true,
        "web_key": "33445566778899abcdef",
        "web_lat": "23.556778",
        "web_long": "8.553641"
    },
    "sensorOD": {
        "adjust_humidity": 0.3,
        "adjust_temp": 0.5,
        "physical": false,
        "web_key": "33445566778899abcdef",
        "web_lat": "23.556778",
        "web_long": "8.553641"
    },
    "mqtt" : {
        "enabled": false,
        "autotopic": false,
        "host": "mqtt-host",
        "port": 1883,
        "syncrate": 60,
        "topic": "",
        "user": "",
        "passwd": "",
        "useha": false
    },
    "rf433": {
        "enabled": true,
        "msgs": [
            { "on": 4333356,"msg": 1, "type":1 },
            { "on": 4333362,"msg": 0, "type":0 }
        ]
        }
}
```

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of ESPAsyncWebServer (and AsyncTCP for ESP32).

### PR DESCRIPTION
**Pull request by mathieucarbou**
Fix #382
WebSocket defragmentation was broken after a fix for Safari in PR #353

This PR refactors several parts:

- The defragmentation handling of the mask (Safari can send it fragmented)
- The defragmentation of the WS frames which was broken since #353 
- The handling of Safari sending invalid disconnect frames
- The logging - which was left but in verbose mode to facilitate debug from users as well

## How to test this PR:

With `WebSocket.ino` example, compile in verbose mode.

**Complete frame**

```bash
# (\n at the end)
> echo hello | websocat ws://192.168.4.1/ws
```

```
ws connect
[310144][V][AsyncWebSocket.cpp:517] _onData(): WS[2]: _onData: plen=12, _pstate=0, _status=1
[310153][V][AsyncWebSocket.cpp:544] _onData(): WS[2]: _pinfo: index: 0, final: 1, opcode: 1, masked: 1, len: 6
[310163][V][AsyncWebSocket.cpp:584] _onData(): WS[2]: mask read complete
[310170][V][AsyncWebSocket.cpp:617] _onData(): WS[2]: processing final fragment index=0, len=6
[310178][V][AsyncWebSocket.cpp:654] _onData(): WS[2]: processing data frame num=0
index: 0, len: 6, final: 1, opcode: 1, framelen: 6
ws text: hello

[310186][V][AsyncWebSocket.cpp:517] _onData(): WS[2]: _onData: plen=6, _pstate=0, _status=1
[310199][V][AsyncWebSocket.cpp:544] _onData(): WS[2]: _pinfo: index: 0, final: 1, opcode: 8, masked: 1, len: 0
[310209][V][AsyncWebSocket.cpp:584] _onData(): WS[2]: mask read complete
[310215][V][AsyncWebSocket.cpp:617] _onData(): WS[2]: processing final fragment index=0, len=0
[310224][V][AsyncWebSocket.cpp:620] _onData(): WS[2]: processing disconnect
[310235][V][AsyncWebSocket.cpp:517] _onData(): WS[2]: _onData: plen=6, _pstate=0, _status=2
[310244][V][AsyncWebSocket.cpp:544] _onData(): WS[2]: _pinfo: index: 0, final: 1, opcode: 10, masked: 1, len: 0
[310254][V][AsyncWebSocket.cpp:584] _onData(): WS[2]: mask read complete
[310260][V][AsyncWebSocket.cpp:617] _onData(): WS[2]: processing final fragment index=0, len=0
[310268][V][AsyncWebSocket.cpp:648] _onData(): WS[2]: processing pong
ws pong
ws disconnect
Connected clients: 1 / 1 total
Free heap: 192416
```

**Fragmentation test:**

```bash
# Generates 2001 characters (\n at the end) to cause a fragmentation (over TCP MSS)
> openssl rand -hex 1000 | websocat ws://192.168.4.1/ws
```

```
ws connect
[492418][V][AsyncWebSocket.cpp:517] _onData(): WS[3]: _onData: plen=1436, _pstate=0, _status=1
[492427][V][AsyncWebSocket.cpp:544] _onData(): WS[3]: _pinfo: index: 0, final: 1, opcode: 1, masked: 1, len: 2001
[492437][V][AsyncWebSocket.cpp:584] _onData(): WS[3]: mask read complete
[492444][V][AsyncWebSocket.cpp:599] _onData(): WS[3]: processing next fragment index=0, len=1428
index: 0, len: 2001, final: 1, opcode: 1, framelen: 1428
ws[/ws][3] [0] MSG START text
ws[/ws][3] [0] FRAME START len=2001
ws[/ws][3] [0] FRAME text, index=0, len=1428]: 7f2c96ab959f566887af03f6d7166c42d25eb8328.........7da971d4b4eedd
[492586][V][AsyncWebSocket.cpp:517] _onData(): WS[3]: _onData: plen=573, _pstate=2, _status=1
[492599][V][AsyncWebSocket.cpp:544] _onData(): WS[3]: _pinfo: index: 1428, final: 1, opcode: 1, masked: 1, len: 2001
[492609][V][AsyncWebSocket.cpp:617] _onData(): WS[3]: processing final fragment index=1428, len=573
[492618][V][AsyncWebSocket.cpp:654] _onData(): WS[3]: processing data frame num=0
index: 1428, len: 2001, final: 1, opcode: 1, framelen: 573
ws[/ws][3] [0] FRAME text, index=1428, len=573]: 3e75adcc607e5236a55c50d9f40ba7aa05a21b3566.........2fbafdff7583cf5225a9252cdac69

ws[/ws][3] [0] FRAME END
ws[/ws][3] [0] MSG END
[492688][V][AsyncWebSocket.cpp:517] _onData(): WS[3]: _onData: plen=6, _pstate=0, _status=1
[492696][V][AsyncWebSocket.cpp:544] _onData(): WS[3]: _pinfo: index: 0, final: 1, opcode: 8, masked: 1, len: 0
[492706][V][AsyncWebSocket.cpp:584] _onData(): WS[3]: mask read complete
[492712][V][AsyncWebSocket.cpp:617] _onData(): WS[3]: processing final fragment index=0, len=0
[492721][V][AsyncWebSocket.cpp:620] _onData(): WS[3]: processing disconnect
[492730][V][AsyncWebSocket.cpp:517] _onData(): WS[3]: _onData: plen=6, _pstate=0, _status=2
[492738][V][AsyncWebSocket.cpp:544] _onData(): WS[3]: _pinfo: index: 0, final: 1, opcode: 10, masked: 1, len: 0
[492748][V][AsyncWebSocket.cpp:584] _onData(): WS[3]: mask read complete
[492755][V][AsyncWebSocket.cpp:617] _onData(): WS[3]: processing final fragment index=0, len=0
[492763][V][AsyncWebSocket.cpp:648] _onData(): WS[3]: processing pong
ws pong
ws disconnect
```

**Safari fragmented packet test**

Hit multiple time CMD+R on Safari => look for `waiting for more mask data: read=0/4`

```
ws connect
ws disconnect
[574838][V][AsyncWebSocket.cpp:517] _onData(): WS[5]: _onData: plen=2, _pstate=0, _status=1
[574847][V][AsyncWebSocket.cpp:544] _onData(): WS[5]: _pinfo: index: 0, final: 1, opcode: 10, masked: 1, len: 0
[574857][V][AsyncWebSocket.cpp:568] _onData(): WS[5]: waiting for more mask data: read=0/4
[574865][V][AsyncWebSocket.cpp:517] _onData(): WS[5]: _onData: plen=4, _pstate=1, _status=1
[574873][V][AsyncWebSocket.cpp:544] _onData(): WS[5]: _pinfo: index: 0, final: 1, opcode: 10, masked: 1, len: 0
[574883][V][AsyncWebSocket.cpp:584] _onData(): WS[5]: mask read complete
[574889][V][AsyncWebSocket.cpp:617] _onData(): WS[5]: processing final fragment index=0, len=0
[574898][V][AsyncWebSocket.cpp:648] _onData(): WS[5]: processing pong
ws pong
[575062][V][AsyncWebSocket.cpp:517] _onData(): WS[5]: _onData: plen=8, _pstate=0, _status=1
[575071][V][AsyncWebSocket.cpp:544] _onData(): WS[5]: _pinfo: index: 0, final: 1, opcode: 8, masked: 1, len: 2
[575080][V][AsyncWebSocket.cpp:584] _onData(): WS[5]: mask read complete
[575087][V][AsyncWebSocket.cpp:617] _onData(): WS[5]: processing final fragment index=0, len=2
[575095][V][AsyncWebSocket.cpp:620] _onData(): WS[5]: processing disconnect
ws disconnect
ws connect
[575155][V][AsyncWebSocket.cpp:517] _onData(): WS[6]: _onData: plen=2, _pstate=0, _status=1
[575164][V][AsyncWebSocket.cpp:544] _onData(): WS[6]: _pinfo: index: 0, final: 1, opcode: 10, masked: 1, len: 0
[575174][V][AsyncWebSocket.cpp:568] _onData(): WS[6]: waiting for more mask data: read=0/4
[575182][V][AsyncWebSocket.cpp:517] _onData(): WS[6]: _onData: plen=4, _pstate=1, _status=1
[575190][V][AsyncWebSocket.cpp:544] _onData(): WS[6]: _pinfo: index: 0, final: 1, opcode: 10, masked: 1, len: 0
[575200][V][AsyncWebSocket.cpp:584] _onData(): WS[6]: mask read complete
[575206][V][AsyncWebSocket.cpp:617] _onData(): WS[6]: processing final fragment index=0, len=0
[575215][V][AsyncWebSocket.cpp:648] _onData(): WS[6]: processing pong
ws pong
```

### CODE REVIEW

File: src/AsyncWebSocket.cpp [hunk 1]
```diff
@@ -541,47 +541,52 @@ void AsyncWebSocketClient::_onData(void *pbuf, size_t plen) {
...
+    async_ws_log_v(
+      "WS[%" PRIu32 "]: _pinfo: index: %" PRIu64 ", final: %" PRIu8 ", opcode: %" PRIu8 ", masked: %" PRIu8 ", len: %" PRIu64, _clientId, _pinfo.index,
+      _pinfo.final, _pinfo.opcode, _pinfo.masked, _pinfo.len
+    );
+
+    // Handle fragmented mask data - Safari may split the 4-byte mask across multiple packets
+    // _pinfo.masked is 1 if we need to start reading mask bytes
+    // _pinfo.masked is 2, 3, or 4 if we have partially read the mask
+    // _pinfo.masked is 5 if the mask is complete
+    while (_pinfo.masked && _pstate <= SATE_FRAME_MASK && _pinfo.masked < 5) {
```
Comment (mathieucarbou) [inline src/AsyncWebSocket.cpp]: reassemble de mask using `_pinfo.masked` to track byte count but resets `_pinfo.masked` to 1 at the end

File: src/AsyncWebSocket.cpp [hunk 2]
```diff
@@ -541,47 +541,52 @@ void AsyncWebSocketClient::_onData(void *pbuf, size_t plen) {
...
+          async_ws_log_v("WS[%" PRIu32 "]: close frame with incomplete mask, treating as unmasked", _clientId);
           _pinfo.masked = 0;
           _pinfo.index = 0;
-        } else {
-          // Wait for more data
-          // async_ws_log_w("WS[%" PRIu32 "]: waiting for more mask data: read=%zu/4", _clientId, mask_offset);
-          _pinfo.index = mask_offset;  // Save progress
-          _pstate = 1;
-          return;
+          _pinfo.len = 0;
```
Comment (mathieucarbou) [inline src/AsyncWebSocket.cpp]: To go into the disconnect use case below

File: src/AsyncWebSocket.cpp [hunk 3]
```diff
@@ -541,47 +541,52 @@ void AsyncWebSocketClient::_onData(void *pbuf, size_t plen) {
...
 
-    // async_ws_log_w("WS[%" PRIu32 "]: _processing data: datalen=%" PRIu32 ", plen=%" PRIu32, _clientId, datalen, plen);
+    // restore masked to 1 for backward compatibility
+    if (_pinfo.masked >= 5) {
+      async_ws_log_v("WS[%" PRIu32 "]: mask read complete", _clientId);
+      _pinfo.masked = 1;
+    }
+
+    const size_t datalen = std::min((size_t)(_pinfo.len - _pinfo.index), plen);
+    const auto datalast = datalen ? data[datalen] : 0;
```
Comment (mathieucarbou) [inline src/AsyncWebSocket.cpp]: I really hate this thing... users have to add `\0` and overflow the data array (see WS examples). That's not normal. I don't know if there is a way to refactor that in a backward compatible way one day.

Comment (willmmiles) [reply src/AsyncWebSocket.cpp]: This hack is outright wrong.  Writing off the end of the `pbuf` pointer is just not safe in a preemptive system.  I've seen crashes because the `onEvent` handler wrote off the end of the buffer, corrupting the heap, and then got pre-empted by another task that tried to do heap allocation before AsyncWebSocket could "undo" the damage.  When I fixed the client, I still saw a crash *because* of the attempt to restore the byte; same setup - preempted during the `onEvent` callback -  but the (now fixed) client didn't overwrite the value; so the heap manager wrote something new to that location, which then had one byte "restored" to an old value when AsyncWebSocket got the CPU back.

Ultimately I had to remove this from the WLED fork and we fixed all our clients to respect the buffer boundaries.  Users don't *have to* write off the end of the array.  It is true that when data arrives as a Pascal-style string (pointer+length), it cannot be used as a C-style string without a copy.  But that's only necessary if you want to interact with C functions; modern tools like `std::string_view` can be used directly.  (And if you must use a C API, `std::string` has a convenient pointer+length constructor for making a quick copy.)

That said: given the current example code, if we consider "onEvent handlers are permitted to write off the end of the buffer by one byte" as part of our backwards compatibilty API contract, then we really have no safe choice but to copy the data into a bigger buffer before calling the callback if the frame ends at the packet boundary.

File: src/AsyncWebSocket.cpp [hunk 4]
```diff
@@ -518,13 +525,6 @@ void AsyncWebSocketClient::_onData(void *pbuf, size_t plen) {
...
 
-      // async_ws_log_w("WS[%" PRIu32 "]: _onData: %" PRIu32, _clientId, plen);
-      // async_ws_log_w("WS[%" PRIu32 "]: _status = %" PRIu32, _clientId, _status);
-      // async_ws_log_w(
-      //   "WS[%" PRIu32 "]: _pinfo: index: %" PRIu64 ", final: %" PRIu8 ", opcode: %" PRIu8 ", masked: %" PRIu8 ", len: %" PRIu64, _clientId, _pinfo.index,
-      //   _pinfo.final, _pinfo.opcode, _pinfo.masked, _pinfo.len
-      // );
-
       data += 2;
       plen -= 2;
```
Comment (willmmiles) [inline src/AsyncWebSocket.cpp]: Availability of these bytes is not checked - in theory `plen` could be 1 here.  This is problematic throughout the header analysis.   Not a new problem for this PR but I'd like to note it nonetheless.

File: src/AsyncWebSocket.cpp [hunk 5]
```diff
@@ -625,24 +638,39 @@ void AsyncWebSocketClient::_onData(void *pbuf, size_t plen) {
...
+      // unexpected frame error, close connection
+      _pstate = SATE_FRAME_START;
+
+      async_ws_log_v("frame error: len: %u, index: %llu, total: %llu\n", datalen, _pinfo.index, _pinfo.len);
+
+      _status = WS_DISCONNECTING;
+      if (_client) {
+        _client->ackLater();
+      }
+      _queueControl(WS_DISCONNECT, data, datalen);
```
[the remark this answers is not in the document]
Comment (willmmiles) [reply src/AsyncWebSocket.cpp]: Good call.

File: src/AsyncWebSocket.cpp (hunk 4 above)
Comment (mathieucarbou) [reply src/AsyncWebSocket.cpp]: Yes I saw that, but we have to look at the WS spec also because these are the first 2 bytes received for the first frame: there shouldn't be any fragmentation there ?
The only case where fragmentation is happening within the assembly of the **frame header** is for the case of Safari which is sending the mask bytes in 2 shots.
