### PR TITLE
Discard bytes after Content-Length

### LINKED ISSUE #100: Client data past Content-Length can crash handlers
### Platform

ESP32

### IDE / Tooling

pioarduino

### What happened?

If a client sends an invalid Content-Length header in a POST or PUT request that is shorter than the data actually sent, handlers may overrun any buffers allocated to the expected Content-Length.  This corrupts the heap, resulting in a crash.

### Stack Trace

```
CORRUPT HEAP: Bad tail at 0x3ffd0ed2. Expected 0xbaad5678 got 0x226e6f22

assert failed: multi_heap_free multi_heap_poisoning.c:279 (head != NULL)

Backtrace: 0x400832ed:0x3ffd02b0 0x4008c19d:0x3ffd02d0 0x40092382:0x3ffd02f0 0x4009108b:0x3ffd0420 0x4008365b:0x3ffd0440 0x400923b5:0x3ffd0460 0x400d97fa:0x3ffd0480 0x400dc545:0x3ffd04a0 0x400d893b:0x3ffd04c0 0x400d8947:0x3ffd04e0 0x4016000a:0x3ffd0500 0x40160116:0x3ffd0530 0x40160382:0x3ffd0550 0x40160403:0x3ffd0580 0x4016046d:0x3ffd05a0 0x4008cba2:0x3ffd05c0

  #0  0x400832ed in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:463
  #1  0x4008c19d in esp_system_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/port/esp_system_chip.c:92
  #2  0x40092382 in __assert_func at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/assert.c:80
  #3  0x4009108b in multi_heap_free at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap_poisoning.c:279 (discriminator 1)
  #4  0x4008365b in heap_caps_free at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/heap_caps_base.c:70
  #5  0x400923b5 in free at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/heap.c:39
  #6  0x400d97fa in AsyncWebServerRequest::~AsyncWebServerRequest() at src/WebRequest.cpp:99
  #7  0x400dc545 in AsyncWebServer::_handleDisconnect(AsyncWebServerRequest*) at src/WebServer.cpp:120 (discriminator 1)
  #8  0x400d893b in AsyncWebServerRequest::_onDisconnect() at src/WebRequest.cpp:267
  #9  0x400d8947 in std::_Function_handler<void (void*, AsyncClient*), AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::{lambda(void*, AsyncClient*)#1}>::_M_invoke(std::_Any_data const&, void*&&, AsyncClient*&&) at src/WebRequest.cpp:51

      (inlined by) __invoke_impl<void, AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::<lambda(void*, AsyncClient*)>&, void*, AsyncClient*> at C:/Users/Will/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/invoke.h:61

      (inlined by) __invoke_r<void, AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::<lambda(void*, AsyncClient*)>&, void*, AsyncClient*> at C:/Users/Will/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/invoke.h:111

      (inlined by) _M_invoke at C:/Users/Will/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/std_function.h:290
  #10 0x4016000a in std::function<void (void*, AsyncClient*)>::operator()(void*, AsyncClient*) const at C:/Users/Will/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/std_function.h:591
  #11 0x40160116 in AsyncClient::_close() at C:/Users/Will/Projects/AsyncTCP/src/AsyncTCP.cpp:1024

      (inlined by) AsyncClient::_close() at C:/Users/Will/Projects/AsyncTCP/src/AsyncTCP.cpp:1017
  #12 0x40160382 in AsyncClient::_poll() at C:/Users/Will/Projects/AsyncTCP/src/AsyncTCP.cpp:1112
  #13 0x40160403 in AsyncClient_detail::handle_async_event(lwip_tcp_event_packet_t*) at C:/Users/Will/Projects/AsyncTCP/src/AsyncTCP.cpp:354
  #14 0x4016046d in _async_service_task(void*) at C:/Users/Will/Projects/AsyncTCP/src/AsyncTCP.cpp:373
  #15 0x4008cba2 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:139
```

### Minimal Reproductible Example (MRE)

Use netcat (or your favorite raw socket program) to send the following text to the Json.ino example:

invalid-json-length.txt:
```
POST /json2 HTTP/1.1
Host: 192.168.4.1
User-Agent: curl/8.11.1
Accept: */*
Content-Type: application/json
Content-Length: 10

{"v":true,"on":true,"bri":128}
```

```sh
$ nc 192.168.4.1 80 < invalid-json-length.txt
```

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of ESPAsyncWebServer (and AsyncTCP for ESP32).

### PR DESCRIPTION
**Pull request by willmmiles**
When accepting an upload, discard any bytes after Content-Length.  This ensures that handlers such as AsyncJson can safely allocate the correct sized buffer without needing to additionally check for overrun.

Fixes #100

### CODE REVIEW

**Review by mathieucarbou — APPROVED** [review]

File: src/WebRequest.cpp [hunk 1]
```diff
@@ -167,6 +167,8 @@ void AsyncWebServerRequest::_onData(void *buf, size_t len) {
       // A handler should be already attached at this point in _parseLine function.
       // If handler does nothing (_onRequest is NULL), we don't need to really parse the body.
       const bool needParse = _handler && !_handler->isRequestHandlerTrivial();
+      // Discard any bytes after content length; handlers may overrun their buffers
+      len = std::min(len, _contentLength - _parsedLength);
```
Comment (me-no-dev) [inline src/WebRequest.cpp:171]: I wonder if it's not worth checking if len is zero and just return in that case. Would happen if more packets are received past the content length.

Comment (mathieucarbou) [reply src/WebRequest.cpp:171]: not return, because if `_parsedLength == _contentLength` we need the if to be executed:

```c++
      if (_parsedLength == _contentLength) {
        _parseState = PARSE_REQ_END;
        _runMiddlewareChain();
        _send();
      }
```

but we also need it to be executed once, which will be the case because `_parsedLength` will be set to PARSE_REQ_END

Comment (mathieucarbou) [reply src/WebRequest.cpp:171]: Also if the content length is more than the bytes sent, we run into the client rx timeout of 5 sec by default, we see: a log like this `[ 30911][D][AsyncTCP.cpp:1160] _poll(): rx timeout 4` and the connection is closed.

Comment (me-no-dev) [reply src/WebRequest.cpp:171]: `_parsedLength == _contentLength` will happen in the last partial packet (the one that sent more data than expected), my question is about a following data packet that is already over the limit.

Comment (me-no-dev) [reply src/WebRequest.cpp:171]: In that case `_parsedLength == _contentLength` will trigger twice

**Review by me-no-dev — APPROVED** [review]
