### PR TITLE
fix: AsyncAbstractResponse might loose part of send buffer

### LINKED ISSUE #315: AsyncAbstractResponse truncates 85 octets in the non-empty segment
### Platform

ESP32

### IDE / Tooling

Arduino (IDE/CLI)

### Versions

esp32 v3.3.2
Async TCP v3.4.9
ESP Async WebServer v3.8.1

### What happened?

My sketch uses a `AsyncAbstractResponse` subclass where `_sendContentLength` is disabled and the `_fillBuffer` function has the following behavior:

1. The first call returns `RESPONSE_TRY_AGAIN`.
2. The second call fully fills the provided buffer with letter "B" and returns `buflen`.
3. The third call fully fills the provided buffer with letter "C" and returns `buflen`.
4. The fourth call returns `0` to end the response.

With the sketch running on either ESP32 or ESP32C3, I invoke `wget` command to trigger the handler.
Downloaded file: [1.txt](https://github.com/user-attachments/files/22985206/1.txt)

The console log pasted below indicates that the sketch has filled 5760 "B"s and 4308 "C"s in the response.
However, the downloaded file has 5675 "B"s and 4308 "C"s.
In other words, 85 octets are truncated off the buffer filled in the second call.

### Stack Trace

```text
WiFi connected
http://192.168.5.67
=========== After Setup Start ============
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   301688 B ( 294.6 KB)
  Free Bytes        :   191032 B ( 186.6 KB)
  Allocated Bytes   :   103632 B ( 101.2 KB)
  Minimum Free Bytes:   190772 B ( 186.3 KB)
  Largest Free Block:   114676 B ( 112.0 KB)
------------------------------------------
GPIO Info:
------------------------------------------
  GPIO : BUS_TYPE[bus/unit][chan]
  --------------------------------------  
    20 : UART_RX[0]
    21 : UART_TX[0]
============ After Setup End =============
_fillBuffer ch=A buflen=5675
_fillBuffer ch=B buflen=5760
_fillBuffer ch=C buflen=4308
_fillBuffer ch=D buflen=4324
```

Wireshark packet trace: [1.pcapng.gz](https://github.com/user-attachments/files/22985245/1.pcapng.gz)

It may or may not be a coincidence, but I noticed:

* The HTTP status line and response headers have exactly 85 octets.
* The `buflen` passed to the first `_fillBuffer` call is 85 larger than the `buflen` passed to the second `_fillBuffer` call.

### Minimal Reproductible Example (MRE)

```cpp
#include <ESPAsyncWebServer.h>
#include <WiFi.h>

static const char* WIFI_SSID = "my-ssid";
static const char* WIFI_PASS = "my-pass";

AsyncWebServer server(80);

class MyResponse : public AsyncAbstractResponse {
public:
  explicit MyResponse() {
    _code = 200;
    _contentType = "text/plain";
    _sendContentLength = false;
  }

  bool _sourceValid() const override {
    return true;
  }

  size_t _fillBuffer(uint8_t* buf, size_t buflen) override {
    Serial.printf("_fillBuffer ch=%c buflen=%zu\n", m_ch, buflen);

    if (m_ch == 'A') {
      ++m_ch;
      return RESPONSE_TRY_AGAIN;
    }
    if (m_ch == 'D') {
      return 0;
    }

    std::fill_n(buf, buflen, static_cast<uint8_t>(m_ch));
    ++m_ch;
    return buflen;
  }

private:
  char m_ch = 'A';
};

void
setup() {
  Serial.begin(115200);
  Serial.println();
  delay(1000);

  WiFi.persistent(false);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  if (WiFi.waitForConnectResult() != WL_CONNECTED) {
    Serial.printf("WiFi failure %d\n", WiFi.status());
    delay(5000);
    ESP.restart();
  }
  Serial.println("WiFi connected");
  delay(1000);

  Serial.print("http://");
  Serial.println(WiFi.localIP());

  server.on("/1.txt", HTTP_GET, [](AsyncWebServerRequest* req) {
    req->send(new MyResponse());
  });
  server.begin();
}

void
loop() {
  delay(1);
}
```

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of ESPAsyncWebServer (and AsyncTCP for ESP32).

### PR DESCRIPTION
**Pull request by vortigont**
`AsyncAbstractResponse::_ack` could allocate temp buffer with size larger than available sock buffer (i.e. to fit headers) and eventually loosing the remainder on transfer due to not checking if the complete data was added to sock buff.

Refactoring code in favor of having a dedicated `std::vector` object acting as accumulating buffer and more careful control on amount of data actually copied to sockbuff

Closes #315

### CODE REVIEW

**Comment by mathieucarbou** [comment]
> BTW is not that same problem #242 ?

It looks like the same indeed!

File: src/WebResponses.cpp [hunk 1]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-      if (len) {
-        --_in_flight_credit;
-      }
-      return 0;
-    }
+      _in_flight += written;
+      --_in_flight_credit;  // take a credit
 #endif
+      request->client()->send();
+      _send_buffer.erase(_send_buffer.begin(), _send_buffer.begin() + written);
```
Comment (mathieucarbou) [inline src/WebResponses.cpp]: could be expensive ?

**Comment by mathieucarbou** [comment]
@vortigont : FYI, I opened PR https://github.com/ESP32Async/ESPAsyncWebServer/pull/317 to add an example in the project that we did not have about large responses.

I was hopping to get the opportunity to reproduce these 2 issues but no, everything goes fine.

Questions:

1) Were you able to reproduce ?
2) If yes, would you be able to rebase your PR on top of https://github.com/ESP32Async/ESPAsyncWebServer/pull/317 and add a handler showing the issue is fixed ?

Thanks!

File: src/WebResponses.cpp [hunk 2]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
+      if (!request->client()->send()){
+        // something is wrong
+        request->client()->close();
+      }
+      return added;
     }
+    // otherwise we've added all the (ramainder) headers in current buff
+    _state = RESPONSE_CONTENT;
+    _assembled_headers = String();  // clear
   }
```
Comment (yoursunny) [inline src/WebResponses.cpp]: Typo: ramainder => remainder

**Review by yoursunny — COMMENTED** [review]
I have verified that the bug has been fixed.
I do not understand the code, but I pointed out some typos in the changes.

File: src/WebResponses.cpp (hunk 1 above)
Comment (vortigont) [reply src/WebResponses.cpp]: I'm not sure, depends on implementation it could be compiler-optimized to something like memmove, but not sure how this is done in espressif's toolchain. But actually I do not expect this part to run frequently under normal conditions, buffer should be aligned with available space.
Other option could be to set additional member var and do index offset calculations.

**Comment by vortigont** [comment]
> I have verified that the bug has been fixed. I do not understand the code, but I pointed out some typos in the changes.

thanks! I'll fix typos :)

File: src/WebResponses.cpp (hunk 1 above)
Comment (vortigont) [reply src/WebResponses.cpp]: actually I do not like this buffer approach at all - it's too heavy in general to create buffer matching window size then copy data there, then copy from buffer to tcp's pcbs. Default Arduino's is 5.7k but with custom-builded lwip it could become a mem hog. Should think of something other - a small fixed-size circular buffer maybe or other type of handlers for objects that could avoid copying

Comment (willmmiles) [reply src/WebResponses.cpp]: I don't think there's an alternative solution at the architectural level -- the interface of `AsyncAbstractResponse` requires that it consume bytes from the implementation only once; and we can't know for sure how many bytes the socket will accept until we send it some; so to be correct, `AsyncAbstractResponse` is going to have to cache the bytes it couldn't send.  Since the API requires it to have a temporary buffer anyways, "just keep the buffer until we've sent it all" is the least bad solution.

Performance wise, `std::vector<>` does hurt a bit though - it both (a) insists on zeroing the memory, and (b) doesn't have easy to use release/reallocate semantics.  I tried using a `default_init_allocator<>` to speed it up, but it didn't help much.  Ultimately in the solution I put together for the fork I've been maintaining for WLED, I ended up making up a more [explicit buffer data structure.](https://github.com/Aircoookie/ESPAsyncWebServer/blob/master/src/DynamicBuffer.h)   I also [wound up doing some gymnastics to avoid allocating so much memory that LwIP couldn't allocate a packet buffer.](https://github.com/Aircoookie/ESPAsyncWebServer/blob/39b830c852054444ea12a8b5d7fcb4fa004a89d7/src/WebResponses.cpp#L301)

See my attempt at a whole solution here: https://github.com/Aircoookie/ESPAsyncWebServer/blob/39b830c852054444ea12a8b5d7fcb4fa004a89d7/src/WebResponses.cpp#L317

Sorry I'm a bit backlogged on pulling this out and pushing it forward...

Some design notes:

- I opted to release the assembly buffer as soon as the data was sent, and reallocate every `_ack`; this keeps the "static" memory usage down and lets it better multiplex between many connections when under memory pressure.
- If I was doing it again, I'd give serious thought to capping the buffer at `TCP_MSS` and looping over `_fillBufferAndProcessTemplates` -> `client()->write()`.  The up side is a guarantee that it'd never be buffering more than one packet; the down side is that it would make ArduinoJSON very sad...

**Comment by mathieucarbou** [comment]
@vortigont : follow-up from https://github.com/ESP32Async/ESPAsyncWebServer/pull/317#issuecomment-3421141039

I just pushed the MRE in the PR and tested it: [51f4472](https://github.com/ESP32Async/ESPAsyncWebServer/pull/316/commits/51f4472e17eba686d6d4615109a424988fe12d88)

```
> curl -s http://192.168.4.1/3 | grep -o '.' | sort | uniq -c

5760 A
4308 B
5760 C
 172 D
```

=> 16000 OK

Console:

```
Filling 'A' @ sent: 0, buflen: 5760
Filling 'B' @ sent: 5760, buflen: 4308
Filling 'C' @ sent: 10068, buflen: 5760
Filling 'D' @ sent: 15828, buflen: 172
```

In main branch, I receive only 15572 bytes indeed: 

```bash
❯  curl http://192.168.4.1/3 | grep -o '.' | sort | uniq -c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15572    0 15572    0     0  18329      0 --:--:-- --:--:-- --:--:-- 18320
5332 A
4308 B
5760 C
 172 D
```

=> 15572

Console

```
Filling 'A' @ sent: 0, buflen: 5760
Filling 'B' @ sent: 5760, buflen: 4308
Filling 'C' @ sent: 10068, buflen: 5760
Filling 'D' @ sent: 15828, buflen: 172
```

So we have a MRE in the project showing that this is fixed 👍

The only issue now remaining is to fix the crash with concurrent requests...

**Comment by vortigont** [comment]
that is... unexpected 8-0, not that that it crashes on alloc but that it does not drop req's on main branch

Here are my results and those are interesting. Yes, this PR ver crashes on high concurrency leveles, but somehow it is **much** faster when not crashing.
I use apache `ab` tool

== this PR
```
Concurrency Level:      10
Time taken for tests:   10.030 seconds
Complete requests:      346
Failed requests:        0
Total transferred:      5729792 bytes
HTML transferred:       5586528 bytes
Requests per second:    34.50 [#/sec] (mean)
Time per request:       289.895 [ms] (mean)
Time per request:       28.990 [ms] (mean, across all concurrent requests)
Transfer rate:          557.86 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        7   59 173.8     29    1100
Processing:    75  220 123.7    193    1151
Waiting:        7   37  10.5     38      68
Total:         82  279 215.7    229    1522
```

== main
```
Concurrency Level:      10
Time taken for tests:   10.002 seconds
Complete requests:      128
Failed requests:        0
Total transferred:      2111312 bytes
HTML transferred:       2057588 bytes
Requests per second:    12.80 [#/sec] (mean)
Time per request:       781.395 [ms] (mean)
Time per request:       78.140 [ms] (mean, across all concurrent requests)
Transfer rate:          206.14 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       11  110 275.1     29    1058
Processing:   389  562 280.2    489    2482
Waiting:      302  378  47.9    368     485
Total:        443  672 387.6    521    2513
```

So it is more that 2.5 times faster, do not ask me how :)

that crappy `autocannon` only gives zeroes to me, have no idea how to interpret it
```
❯ autocannon -w 10 -c 10 http://192.168.8.26/2
Running 10s test @ http://192.168.8.26/2
10 connections
10 workers

-
┌─────────┬──────┬──────┬───────┬──────┬──────┬───────┬──────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg  │ Stdev │ Max  │
├─────────┼──────┼──────┼───────┼──────┼──────┼───────┼──────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │
└─────────┴──────┴──────┴───────┴──────┴──────┴───────┴──────┘
┌───────────┬─────┬──────┬─────┬───────┬─────┬───────┬─────┐
│ Stat      │ 1%  │ 2.5% │ 50% │ 97.5% │ Avg │ Stdev │ Min │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Req/Sec   │ 0   │ 0    │ 0   │ 0     │ 0   │ 0     │ 0   │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 0 B │ 0 B   │ 0 B │ 0 B   │ 0 B │
└───────────┴─────┴──────┴─────┴───────┴─────┴───────┴─────┘

Req/Bytes counts sampled once per second.
# of samples: 100

156 requests in 10.02s, 0 B read

```

I'll think about replacing this `std::vector` buffer on something more static and controllable, a small circ buffer maybe, but it will take a bit more time for trial and error.

**Comment by vortigont** [comment]
yeah, I'm using `/2` for testing now, it crashes with `ab` with connections above 10 too.
Memory pressure is much higher with this PR, but so as the performance. Scratching head...

Autocannon does not give me any readable stat at all, it just runs requests then quits with zeroes in output. Works but quite useless for any analysis.

```
➜ autocannon -w 16 -c 16 -a 32 http://192.168.8.26/2
Running 32 requests test @ http://192.168.8.26/2
16 connections
16 workers

/
┌─────────┬──────┬──────┬───────┬──────┬──────┬───────┬──────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg  │ Stdev │ Max  │
├─────────┼──────┼──────┼───────┼──────┼──────┼───────┼──────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │
└─────────┴──────┴──────┴───────┴──────┴──────┴───────┴──────┘
┌───────────┬─────┬──────┬─────┬───────┬─────┬───────┬─────┐
│ Stat      │ 1%  │ 2.5% │ 50% │ 97.5% │ Avg │ Stdev │ Min │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Req/Sec   │ 0   │ 0    │ 0   │ 0     │ 0   │ 0     │ 0   │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 0 B │ 0 B   │ 0 B │ 0 B   │ 0 B │
└───────────┴─────┴──────┴─────┴───────┴─────┴───────┴─────┘

Req/Bytes counts sampled once per second.
# of samples: 31

32 requests in 1.01s, 0 B read

```

**Comment by mathieucarbou** [comment]
> that is... unexpected 8-0, not that that it crashes on alloc but that it does not drop req's on main branch

@vortigont  just to clarify:

### examples/LargeResponse

I did my testing:
- with the handler at /2 of examples/LargeResponse
- **AP mode** (using the example)

**In main:** /2 handler works (16000 bytes).
**In this PR:** /2 handler fails either constantly or randomly depending how requests arrive

I did not use the /3 handler for my testing: it just acts as a MRE to reproduce the is issue

Using `ab -c 16 -t 10 http://192.168.4.1/2` I can reproduce the crash. Even with `-c 10`. 

But in both cases, it is random. I have to restart ab several times to trigger it while I get to reproduce it more easily with autocannon.

### examples/PerfTests

**- For request serving:** 

This is insanely fast! We were barely reaching 13 req/s before on average! This is more like 5-6 times faster!

```bash
❯  autocannon -c 16 -w 16 -d 20 --renderStatusCodes http://192.168.4.1
Running 20s test @ http://192.168.4.1
16 connections
16 workers

\
┌─────────┬────────┬─────────┬──────────┬──────────┬────────────┬────────────┬──────────┐
│ Stat    │ 2.5%   │ 50%     │ 97.5%    │ 99%      │ Avg        │ Stdev      │ Max      │
├─────────┼────────┼─────────┼──────────┼──────────┼────────────┼────────────┼──────────┤
│ Latency │ 206 ms │ 4246 ms │ 11578 ms │ 12129 ms │ 4749.38 ms │ 3246.55 ms │ 14444 ms │
└─────────┴────────┴─────────┴──────────┴──────────┴────────────┴────────────┴──────────┘
┌───────────┬────────┬────────┬────────┬────────┬────────┬─────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%    │ 97.5%  │ Avg    │ Stdev   │ Min    │
├───────────┼────────┼────────┼────────┼────────┼────────┼─────────┼────────┤
│ Req/Sec   │ 44     │ 44     │ 69     │ 80     │ 68.16  │ 7.75    │ 44     │
├───────────┼────────┼────────┼────────┼────────┼────────┼─────────┼────────┤
│ Bytes/Sec │ 193 kB │ 193 kB │ 302 kB │ 350 kB │ 298 kB │ 33.9 kB │ 193 kB │
└───────────┴────────┴────────┴────────┴────────┴────────┴─────────┴────────┘
┌──────┬───────┐
│ Code │ Count │
├──────┼───────┤
│ 200  │ 1363  │
└──────┴───────┘

Req/Bytes counts sampled once per second.
# of samples: 320

3k requests in 20.03s, 5.97 MB read
200 errors (0 timeouts)
```

File: src/WebResponses.cpp [hunk 3]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-      //  take the credit back since we are ignoring this ack and rely on other inflight data
-      if (len) {
-        --_in_flight_credit;
-      }
-      return 0;
-    }
+      _in_flight += written;
+      --_in_flight_credit;  // take a credit
 #endif
+      request->client()->send();
```
Comment (mathieucarbou) [inline src/WebResponses.cpp]: what if send() returns false ? should we instead keep the data and retry ?

Comment (vortigont) [reply src/WebResponses.cpp]: I was checking this and as I understood it does not make sense to keep the data.
it may return false in case TCP window is closed or connection is broken already.
In first case the data is in tcp buffs already, so it will send later, in second it is useless anyway. Kind of like this if I got it right

File: src/WebResponses.cpp [hunk 4]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-
-    if (headLen) {
-      _head = emptyString;
     }
 
-    if (outLen) {
-      _writtenLength += request->client()->write((const char *)buf, outLen);
+    size_t written{0};
+    if (_send_buffer.size()){
+      written = request->client()->add(reinterpret_cast<char*>(_send_buffer.data()), _send_buffer.size());
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: well, it depends on how to read it :) it might be `written to tcp buffs` not to the wire (air).
As long as you've `add`ed data and `send()` it is up to lwip to deliver it sooner or later depending on TCP window state from the remote side. Same thing with `ack`s - it is confusingly named `acknowledge` while it does not acknowledge the delivery itself, it is done with tcp ack's, but it is called on window updates from the remote side.
Using this technique I've implemented flow control [here](https://github.com/ESP32Async/ESPAsyncWebServer/pull/312/commits/06f565963532b6ef77dc37ba9ce1726219d5d0e1), where websock can inhibit remote side from sending us more data when not needed

File: src/WebResponses.cpp [hunk 5]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
+    _assembled_headers = String();  // clear
   }
 
-  if (_state == RESPONSE_CONTENT) {
+  // if there are leftovers in buffer from the previous run, let's deal with it first
+  if (_state == RESPONSE_CONTENT && _send_buffer.size()){
+    size_t const written = request->client()->add(reinterpret_cast<char*>(_send_buffer.data()), _send_buffer.size());
+    if (written != _send_buffer.size()){
+      // we were not able to fit entire buffer again?! OK, let's send partial now and come back later
+      _writtenLength += written;
```
Comment (mathieucarbou) [inline src/WebResponses.cpp]: _writtenLength : before it was updated only after a send() : write() was doing add() + send()

File: src/WebResponses.cpp [hunk 6]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-      _state = RESPONSE_CONTENT;
-      space -= headLen;
-    } else {
-      String out = _head.substring(0, space);
-      _head = _head.substring(space);
-      _writtenLength += request->client()->write(out.c_str(), out.length());
-#if ASYNCWEBSERVER_USE_CHUNK_INFLIGHT
-      _in_flight += out.length();
+    // copy headers buffer to sock buffer
+    size_t const added = request->client()->add(_assembled_headers.c_str() + _assembled_headers_sent, _assembled_headers.length() - _assembled_headers_sent);
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: we need `added`  value as returned from `add()` to increment `_writtenLength` var.
But you've got the right spot, this comparison might be wrong `if (added < _assembled_headers.length())`
it is valid for only 1st check, if headers a so large not to fit into 1st call further calculation would be wrong. I will fix it

[the remark this answers is not in the document]
Comment (mathieucarbou) [reply src/WebResponses.cpp]: Can it happen in real life ? 
the client space should be nearly empty at this point since headers are the first thing we write ?
It would require then to be several Kbytes long to overflow and be sent in 2 rounds ?

File: src/WebResponses.cpp [hunk 7]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
+      #if ASYNCWEBSERVER_USE_CHUNK_INFLIGHT
+      _in_flight += added;
       --_in_flight_credit;  // take a credit
-#endif
-      return out.length();
+      #endif
+      if (!request->client()->send()){
+        // something is wrong
+        request->client()->close();
+      }
```
[the remark this answers is not in the document]
Comment (mathieucarbou) [reply src/WebResponses.cpp]: > What is the purpose of returned value of `size_t AsyncAbstractResponse::_ack`? I was unable to narrow it down.

This is the async_tcp callback to notify us about how many bytes were received by the client.

We have another implementation here: `size_t AsyncBasicResponse::_ack(AsyncWebServerRequest *request, size_t len, uint32_t time)` implementation, `_writtenLength` 

In this one, it match the # of bytes sent on the wire IMO to be compared with the _ackedLength.

Similar to an example I did in async_tcp lib to show to someone how to "wait" for  client to receive the data before sending the next round.

https://github.com/ESP32Async/AsyncTCP/blob/a04bdcc2d96f2e180953fad9f70ccb70f778be49/examples/AsyncSend/AsyncSend.ino#L111-L115

In the case of asyncws, it is also called with len=0 and time= on poll events.

So I guess that in your PR if you were to reuse this mechanism, you would need to use it to check for `_ackedLength >= _writtenLength`

But the way you did it, if you do not compare _ackedLength with bytes sent, **could it be where the speed improvement comes from** ? You are sending the request, but just ensure it is sent, but do not verify that the client ack all the bytes ?

I don't know what kind of bad behavior this change could trigger ?

File: src/WebResponses.cpp [hunk 8]
```diff
@@ -364,127 +364,139 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
+    return written;
+  }
+  
+  if (_state == RESPONSE_WAIT_ACK) {
+    // we do not need to wait for any acks actually if we won't send any more data,
+    // connection would be closed gracefully with last piece of data
+    _state = RESPONSE_END;
+    request->client()->close();
   }
   return 0;
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: BTW I've specifically analyzed captures for this case, it behaves so nice - the last payload data packet from ESP's side comes with FIN bit set and then it completes with FIN/ACK from receiver side. It saves 2 turnarounds :)

[the remark this answers is not in the document]
Comment (mathieucarbou) [reply src/WebResponses.cpp]: > Umm... I do not like the idea of user flags, with all due respect to users :) I'd be better think on some kind of memory control technique, a middleware could be an option here?
> 
> OK, enough for today for me :) let's see another day

Yes could be! Middleware can act on a request before processing by the handler or on a response after the handler. But in any case it will be before the asynws api asks for the data to send. I don't know what you have in mind though with that idea ;-)

**Comment by vortigont** [comment]
A bit different approach - a fixed-size buffer that is created on-demand and released upon send call unless not all data was copied to sock buffs for some reason. No realloc's, using offset pointers, also knowing @willmmiles's challenges created it as a no-throwing allocated with fallback. Though did not went that far as to allocate per single packet buffer.

File: src/WebRequest.cpp [hunk 9]
```diff
@@ -33,66 +33,66 @@ AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer *s, AsyncClient *c)
...
     this
   );
 }
 
 AsyncWebServerRequest::~AsyncWebServerRequest() {
-  // async_ws_log_e("AsyncWebServerRequest::~AsyncWebServerRequest");
+  if (_client){
+    // usually it is _client's disconnect triggers object destruct, but for completeness we define behavior
+    // if for some reason *this will be desturcted while client is still connected
+    _client->onDisconnect(nullptr);
```
Comment (mathieucarbou) [inline src/WebRequest.cpp]: in which case it can happen that `onDisconnect` is not called ? I remember we have checked with @willmmiles and it is called from lwip layer. There would also be some memory leaks if it was not the case.

File: src/WebResponses.cpp [hunk 10]
```diff
@@ -354,138 +349,148 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-      buf[outLen++] = '\n';
-      outLen += readLen;
-      buf[outLen++] = '\r';
-      buf[outLen++] = '\n';
-    } else {
-      readLen = _fillBufferAndProcessTemplates(buf + headLen, outLen);
-      if (readLen == RESPONSE_TRY_AGAIN) {
-        free(buf);
+  // send http headers first
+  if (_state == RESPONSE_HEADERS) {
```
Comment (mathieucarbou) [inline src/WebResponses.cpp]: This case seems to be nearly the same code as in AsyncBasicResponse, right ?
If yes, why not moving it to a protected function like _sendheaders() which could return the # of bytes sent ?
the inflight code would stay here and be executed only if _sendheaders() returns something ?

File: src/WebResponses.cpp [hunk 11]
```diff
@@ -354,138 +349,148 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
+          _send_buffer->at(readLen + 7) = '\n';
+          _send_buffer_len += readLen + 8;      // set buffers's size to match added data
+          _sentLength += readLen;               // data is not sent yet, but we won't get a chance to count this later properly for chunked data
+          if (!readLen){
+            // last chunk?
+            _state = RESPONSE_END;
+          }
+        }
+      } else {
+        size_t const readLen = _fillBufferAndProcessTemplates(_send_buffer->data(), std::min(_send_buffer->size(), tcp_win));
```
Comment (mathieucarbou) [inline src/WebResponses.cpp]: should `p` be allocated depending on this if / else case to optimize ?

for example for json responses, where we have a _contentLength, it would make sense to allocate it to max win size (CONFIG_LWIP_TCP_MSS) and not ASYNC_RESPONCE_BUFF_SIZE ?

I might not understand why `ASYNC_RESPONCE_BUFF_SIZE CONFIG_LWIP_TCP_MSS * 2` also...

File: src/WebResponses.cpp [hunk 12]
```diff
@@ -354,138 +349,148 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-    } else {
-      _sentLength += outLen - headLen;
-    }
+      auto tcp_win = request->client()->space();
+      if (tcp_win == 0 || _state == RESPONSE_END)
+        break;  // no room left or no more data
 
-    free(buf);
+      if ((_chunked || !_sendContentLength) && (tcp_win < CONFIG_LWIP_TCP_MSS / 2)) {
+        // available window size is not enough to send a new chunk sized half of tcp mss, let's wait for better chance and reduce pressure to AsyncTCP's event Q
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: It is per connection, so concurrent cases are not affected.
Small payload (by small I mean less then default snd_buff_size => 4*MSS=5,7k ) is also not affected.

With that refilling buffer method while digging through captures I noticed a strange behavior - even if `add()`ing lwip's buffer data with large chunks only, I could see esp sends small packets with 16 byte payload for about every snd_buff rollover.
It should not happen as send buffer is 4*MSS exactly, but looks like `space()` call sometimes return unaligned sizing. Do not know why, needs digging deep into lwip which we can't control much anyway.
So this 16 bytes of send payload then returns back being `_ack` called with `len` value of 16 again, and if not ignored here would result in sending another 16 bytes small payload again amplifying this small packets cycle.

To mitigate this there are 2 options:
 - ignore those 16 bytes `_ack` calls (or similar cases when snd buff is almost filled)
 - deduct that 16 bytes from buff size arg passed to any client's callback

Since I was unable to understand the origin of such behavior I opted to take a more general approach - if `tcp_win` (the amount of data we could add to buffer) is so small that it won't fit half of MSS (~700 bytes or 1/8 of default's snd_buff size) we refuse to add more data to send buffer here and wait for next ack call. The buffer anyway is 7/8 full, so it has plenty of data to send for now. And  for chunked / unknown len responses we are supposed to send large pieces of data so this 700 bytes top won't make much difference.

Note: here `tcp_win` is not 100% correct name 'cause actually it is `min(snd_buff_free, tcp_win)` but I do not have more feasible naming for now, open for suggestions here :)

image

image

Here you can see that - both should be 1436 which is the MSS size.

File: src/WebResponses.cpp [hunk 13]
```diff
@@ -354,138 +349,148 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
-      _writtenLength += request->client()->write((const char *)buf, outLen);
-#if ASYNCWEBSERVER_USE_CHUNK_INFLIGHT
-      _in_flight += outLen;
-      --_in_flight_credit;  // take a credit
-#endif
-    }
+  // send content body
+  if (_state == RESPONSE_CONTENT) {
+    do {
+      if (_send_buffer_len && _send_buffer){
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: not really but since those are two different objects not tied to each other and `_send_buffer` could be a nullptr it's just to be on a safe side here, for vector it was just vector's `size()`.

File: src/WebRequest.cpp (hunk 9 above)
Comment (vortigont) [reply src/WebRequest.cpp]: it's a bookmark for future.
This is another white spot that confuses me - current design does not specify strict ownership and relation between AsyncTCPClient's object, webserver, request obj and responce obj. Those all are just bare pointers which are created and assigned/deassigned willingly. For me it is still not obvious to track the ownership and destruction.
I.e. we have this in in `AsyncWebServer`:

https://github.com/ESP32Async/ESPAsyncWebServer/blob/b67f0e948989e73bda4c715c0e5dc6926880b61a/src/WebServer.cpp#L47-L51

where `AsyncClient` is deleted if request was not created. Logically it means that if it `was` created successfully then it's up to `AsyncWebServerRequest` to delete it further, while currently it is not. And the request object is self destructs itself by passing `this*` to webserver.
Also client could be passed between req/responce objects and sometimes even detached from those (i.e. in websockets).
Sooner or later we'd have to redesign it all, bring in smart-pointers / queues / lists and strict ownership tracking. Do not have all the answers for now.

File: src/WebResponses.cpp [hunk 14]
```diff
@@ -265,70 +269,61 @@ AsyncBasicResponse::AsyncBasicResponse(int code, const char *contentType, const
...
-      _state = RESPONSE_WAIT_ACK;
-      return available;
+  size_t payloadlen{0};  // amount of data to be written to tcp sockbuff during this call, used as return value of this method
+
+  // send http headers first
+  if (_state == RESPONSE_HEADERS) {
+    // copy headers buffer to sock buffer
+    size_t const pcb_written = request->client()->add(_assembled_headers.c_str() + _assembled_headers_written, _assembled_headers.length() - _assembled_headers_written);
+    _writtenLength += pcb_written;
+    _assembled_headers_written += pcb_written;
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: you mean `_assembled_headers_written` - > `_writtenHeadersLength`?
Sounds good for me )

File: src/WebResponses.cpp [hunk 15]
```diff
@@ -354,138 +349,148 @@ size_t AsyncAbstractResponse::_ack(AsyncWebServerRequest *request, size_t len, u
...
+        // available window size is not enough to send a new chunk sized half of tcp mss, let's wait for better chance and reduce pressure to AsyncTCP's event Q
+        break;
+      }
 
-    if ((_chunked && readLen == 0) || (!_sendContentLength && outLen == 0) || (!_chunked && _sentLength == _contentLength)) {
-      _state = RESPONSE_WAIT_ACK;
-    }
-    return outLen;
+      if (!_send_buffer){
+        auto p = new (std::nothrow) std::array<uint8_t, ASYNC_RESPONCE_BUFF_SIZE>;
```
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: right, it could be as low as 200 bytes if needed with 10 times iterations.
But currently that buffer does not persist between `_ack()` calls and since it is called from that single AsyncTCP's thread it does not matter how large this buffer is, it is temporary for one call only _unless_ there is so much mem pressure that lwip can't allocate buffers for itself. In this case we'd have to save the buffer between calls that serve different tcp sessions and make even more pressure to heap mem.
It is not that this buffer will stress mem, it will be lwip's pcb's parts, they do not account anything but snd_buff_size top watermark and tcp_win size, so it will eat your all mem anyway either via copying from large buff once or many times from small one :)
The tradeoff is tricky here, what is more priority for small MCU - serve as much parallel session as possible slowing down everyone at same time or try to serve a finite number of connections pushing back new ones. Could use different approaches here.

I'd rather not to leave it to user's choice on a per request basis. Picking better size could be a complicated task highly depended on many factors.
We could possibly extend current `AsyncAbstractResponse` constructor with size arg for buffer, but I'd think twice on this. Improper sizing could end up with buffer not released between `_ack()` calls and ruin the whole idea.
Also currently it's `std::array`, it need compile-time sizing, have to switch back to std::vector or bare `malloc`.
Maybe think on some more architecture changes and define this policy on per content type along with of some generic middle-ware that guards entire server's health. Kind of connections pool/queue that are serviced on preemptive priority bases - long term perspective.

As for Jsons (always jsons) We have to keep source JsonDocument in mem, interim buffer and lwip will allocate more for sending - worst case scenario :)
I do not know if it worth the efforts to shrink intermediate buffer to smaller values, reiterate many times and try to keep up with multiple connections? I do not have use-cases like this in mind. Personally I'd take architecture decisions - hard-limit number of parallel responses with large json objects, switch to websockets or change MCU :)
I did not checked middleware close enough, would it be possible for middleware to affect the parameters of parent response object based on assigned callback?
Let's maybe think it trough further out of this scope.

Also to consider: current response's API enforces using this intermediate buffer even for the data sources where it is not needed at all. For ex. serving RO-data does not need this, we could just pass pointer to the data to client's `add()` calls, no buffering.
Same applies for certain cases like exactly that cam project where this issue comes from - we already have data somewhere in mem and it won't go away unless we send it all. So, why bother double buffering it when could just give the pointer to responce and say, go ahead, send it and let me know when it's over.
I've implemented it here in [new websocket API](https://github.com/ESP32Async/ESPAsyncWebServer/pull/312/commits/ba4ab0707979156d0f18c7296d8fe706dfa23b77)
But for web server we'd need some API breaking changes.

File: src/WebResponses.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (me-no-dev) [reply src/WebResponses.cpp]: @vortigont good find! We can surely adjust this for the future

[the remark this answers is not in the document]
Comment (me-no-dev) [reply src/WebResponses.cpp]: @vortigont PR is here: https://github.com/espressif/esp32-arduino-lib-builder/pull/325
You could grab the libs that it will build and give this a shot maybe?

[the remark this answers is not in the document]
Comment (mathieucarbou) [reply src/WebResponses.cpp]: @vortigont  it should also be possible to test with pioarduino hybrid compilation feature by adding that to the environment.

We have an example already in the project in the pio_arduino example folder:

```ini
custom_sdkconfig = CONFIG_LWIP_TCP_SND_BUF_DEFAULT=5744
```

will output:

```
============================
CONFIG_LWIP_TCP_SND_BUF_DEFAULT 5744
============================
```

(replacing `CONFIG_LWIP_MAX_ACTIVE_TCP` with `CONFIG_LWIP_TCP_SND_BUF_DEFAULT`)

File: src/WebResponses.cpp (hunk 11 above)
Comment (mathieucarbou) [reply src/WebResponses.cpp]: Ok I see... So it depends on the network / client speed maybe ? For example, if we have a very slow client / network sending its ack slower than we are able to send data, then it will mean one CONFIG_LWIP_TCP_MSS sent per round, compared to a client processing data fact and sending ack fast, would allow us to send up to 2 times CONFIG_LWIP_TCP_MSS in a round ?

**Comment by mathieucarbou** [comment]
@vortigont :

- I merged main into this branch to make it up to date
- I added back the MRE in the `LargeResponse` example that I added and was probably removed following a force push
- I fixed the ci checks
- **I found a bug also:**

If you run the PerfTest example and triggers 16 SSE clients:

`for i in {1..16}; do ( count=$(gtimeout 30 curl -s -N -H "Accept: text/event-stream" http://192.168.4.1/events 2>&1 | grep -c "^data:"); echo "Total: $count events, $(echo "$count / 4" | bc -l) events / second" ) & done;`

```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400daaa6  PS      : 0x00060b30  A0      : 0x800daac4  A1      : 0x3ffd1690  
  #0  0x400daaa6 in AsyncWebServerRequest::_onAck(unsigned int, unsigned long) at src/WebRequest.cpp:234
      (inlined by) AsyncWebServerRequest::_onAck(unsigned int, unsigned long) at src/WebRequest.cpp:225

A2      : 0x3ffd28d8  A3      : 0x0000007a  A4      : 0x00000014  A5      : 0x0000e280  
A6      : 0x00000000  A7      : 0x0000abab  A8      : 0x800daaa4  A9      : 0x3ffd1670  
A10     : 0x00000000  A11     : 0x3ffd28d8  A12     : 0x0000007a  A13     : 0x00000014  
A14     : 0x00000003  A15     : 0x3ffd35f4  SAR     : 0x0000001c  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x40088a7c  LEND    : 0x40088a87  LCOUNT  : 0xffffffff  


Backtrace: 0x400daaa3:0x3ffd1690 0x400daac1:0x3ffd16b0 0x400d5c4f:0x3ffd16d0 0x400d65db:0x3ffd1700 0x400d678d:0x3ffd1720 0x4008c3f5:0x3ffd1750
  #0  0x400daaa3 in AsyncWebServerRequest::_onAck(unsigned int, unsigned long) at src/WebRequest.cpp:232
      (inlined by) AsyncWebServerRequest::_onAck(unsigned int, unsigned long) at src/WebRequest.cpp:225
  #1  0x400daac1 in std::_Function_handler<void (void*, AsyncClient*, unsigned int, unsigned long), AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::{lambda(void*, AsyncClient*, unsigned int, unsigned long)#1}>::_M_invoke(std::_Any_data const&, void*&&, AsyncClient*&&, unsigned int&&, unsigned long&&) at src/WebRequest.cpp:44
      (inlined by) __invoke_impl<void, AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::<lambda(void*, AsyncClient*, size_t, uint32_t)>&, void*, AsyncClient*, unsigned int, long unsigned int> at /Users/mat/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/invoke.h:61
      (inlined by) __invoke_r<void, AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::<lambda(void*, AsyncClient*, size_t, uint32_t)>&, void*, AsyncClient*, unsigned int, long unsigned int> at /Users/mat/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/invoke.h:111
      (inlined by) _M_invoke at /Users/mat/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/std_function.h:290
  #2  0x400d5c4f in std::function<void (void*, AsyncClient*, unsigned int, unsigned long)>::operator()(void*, AsyncClient*, unsigned int, unsigned long) const at /Users/mat/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/std_function.h:591
      (inlined by) AsyncClient::_sent(tcp_pcb*, unsigned short) at .pio/libdeps/arduino-3/AsyncTCP/src/AsyncTCP.cpp:1055
  #3  0x400d65db in AsyncTCP_detail::handle_async_event(lwip_tcp_event_packet_t*) at .pio/libdeps/arduino-3/AsyncTCP/src/AsyncTCP.cpp:300
  #4  0x400d678d in _async_service_task(void*) at .pio/libdeps/arduino-3/AsyncTCP/src/AsyncTCP.cpp:328
  #5  0x4008c3f5 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:139
```

**Comment by vortigont** [comment]
> I suspect this is because of the while loop added in the new _ack implementation ?

yeah... with iterative refill we can't accept such delays each cycle. Well... what can I say - it's async lib, do not do this or watch dog will bite :))

File: src/WebResponses.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (vortigont) [reply src/WebResponses.cpp]: yes, but in this chain `ROM-> interim buffer -> TCP buffer` the middle one could be skipped for many cases. I.e. if it's gzipped blob in ROM or some other bulk data in RAM prepared for sending.
But we are bound here with `_fillBuffer` API and dependency on having template processor, so it would need a more deeper refactoring.

File: src/ESPAsyncWebServer.h [hunk 16]
```diff
@@ -305,6 +305,19 @@ class AsyncWebServerRequest {
...
+   * @brief release owned AsyncClient object
+   * AsyncClient pointer will be abandoned in this instance,
+   * the further ownership of the connection should be managed out of request's life-time scope
+   * could be used for long lived connection like SSE or WebSockets
+   * @note do not call this methos unless you know what you are doing, otherwise it may lead to
+   * memory leaks and connections lingering
+   * 
+   * @return AsyncClient* pointer to released connection object
+   */
+  AsyncClient* clientRelease();
```
Comment (mathieucarbou) [inline src/ESPAsyncWebServer.h]: should this be made private or protected and eventually use friend if needed ?

File: src/AsyncEventSource.cpp [hunk 17]
```diff
@@ -482,13 +481,23 @@ AsyncEventSourceResponse::AsyncEventSourceResponse(AsyncEventSource *server) {
...
-size_t AsyncEventSourceResponse::_ack(AsyncWebServerRequest *request, size_t len, uint32_t time __attribute__((unused))) {
-  if (len) {
-    new AsyncEventSourceClient(request, _server);
-  }
-  return 0;
-}
+void AsyncEventSourceResponse::_switchClient(){
+  // AsyncEventSourceClient c-tor will take the ownership of AsyncTCP's client connection
+  new AsyncEventSourceClient(_request, _server);
+  // AsyncEventSourceClient c-tor would also delete _request and *this
```
Comment (mathieucarbou) [inline src/AsyncEventSource.cpp]: I did not notice the `delete request;` in this c-tor ! I understand now!

**Comment by mathieucarbou** [comment]
> why is that request pointer passed to user's callback, any idea? I mean is there any use case for it? Otherwise would have to keep `request` ptr till callback compltes.

The request ptr is not passed to public api: `_newClient ` is closed api. Only the ws client object is passed.

On of the useful thing is:
-  to identify the client: client->id() or using client ptr directly
- to call client->ping()
- to call client->setCloseClientOnQueueFull(false);

I might not understand your question ?

**Comment by vortigont** [comment]
> I might not understand your question ?

yeah, sorry, I mean here

`_handleEvent(&_clients.back(), WS_EVT_CONNECT, nullptr /* request */, NULL, 0);`

3rd arg was `request` (here replaced with nullptr), which then passed as `void*` to user's callback to handle ws connect event. It is in addition to `client*`, I never used it in my code anywhere, do not know if there could be any use of getting `request` obj pointer in websocket-related callback.

**Comment by vortigont** [comment]
yeah, you right, that makes sense to get extensions from headers.
OK, not a big deal, I'll move it. It is for `connect` event only, right? We do not need to keep it further during whole ws connecton life-time, do we?

**Comment by mathieucarbou** [comment]
> yeah, you right, that makes sense to get extensions from headers. OK, not a big deal, I'll move it. It is for `connect` event only, right? We do not need to keep it further during whole ws connecton life-time, do we?

This is only for connect yes... After that, the arg is casted in a AwsFrameInfo for data events

**Comment by mathieucarbou** [comment]
> his PR causes a regression in template processing.

Thanks a lot for participating in this PR's testing!

**Comment by mathieucarbou** [comment]
> This simple issue fix has already went too way out of it's initial scope :))

You mean was more impactful than initially thought 😀 

I will take time this morning to test again the other parts. For now we always discovered bad side effects / crashes so that’s ok to make sure that this (complex) fix is well tested and does not crash / impact other ones.

**Comment by mathieucarbou** [comment]
> mean could have just fix the problem without further enhancements and regressions :))) But anyway, it is what it is. Not sure what to do with that templating, I guess it should work as-is since it's just same buffer, but somehow it places a NULL byte at the beginning.

I don't understand either why your change impacts templating and not other endpoints. That's what I will try to check.

**Comment by mathieucarbou** [comment]
@vortigont : test results:

```bash
❯  autocannon -c 16 -w 16 -d 20 --renderStatusCodes  http://192.168.4.1/
Running 20s test @ http://192.168.4.1/
16 connections
16 workers

/
┌─────────┬────────┬─────────┬──────────┬──────────┬────────────┬────────────┬──────────┐
│ Stat    │ 2.5%   │ 50%     │ 97.5%    │ 99%      │ Avg        │ Stdev      │ Max      │
├─────────┼────────┼─────────┼──────────┼──────────┼────────────┼────────────┼──────────┤
│ Latency │ 220 ms │ 4809 ms │ 11013 ms │ 11514 ms │ 4935.47 ms │ 3134.86 ms │ 12016 ms │
└─────────┴────────┴─────────┴──────────┴──────────┴────────────┴────────────┴──────────┘
┌───────────┬────────┬────────┬────────┬────────┬────────┬───────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%    │ 97.5%  │ Avg    │ Stdev │ Min    │
├───────────┼────────┼────────┼────────┼────────┼────────┼───────┼────────┤
│ Req/Sec   │ 56     │ 56     │ 68     │ 79     │ 67.66  │ 5.48  │ 56     │
├───────────┼────────┼────────┼────────┼────────┼────────┼───────┼────────┤
│ Bytes/Sec │ 245 kB │ 245 kB │ 298 kB │ 346 kB │ 296 kB │ 24 kB │ 245 kB │
└───────────┴────────┴────────┴────────┴────────┴────────┴───────┴────────┘
┌──────┬───────┐
│ Code │ Count │
├──────┼───────┤
│ 200  │ 1353  │
└──────┴───────┘

Req/Bytes counts sampled once per second.
# of samples: 320

3k requests in 20.14s, 5.92 MB read
180 errors (0 timeouts)
```

```bash
❯  ab -c 16 -t 20 http://192.168.4.1/
This is ApacheBench, Version 2.3 <$Revision: 1913912 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.168.4.1 (be patient)
Finished 1377 requests


Server Software:        
Server Hostname:        192.168.4.1
Server Port:            80

Document Path:          /
Document Length:        4272 bytes

Concurrency Level:      16
Time taken for tests:   20.001 seconds
Complete requests:      1377
Failed requests:        0
Total transferred:      6003946 bytes
HTML transferred:       5886816 bytes
Requests per second:    68.85 [#/sec] (mean)
Time per request:       232.398 [ms] (mean)
Time per request:       14.525 [ms] (mean, across all concurrent requests)
Transfer rate:          293.15 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        9  145 429.6     28    5073
Processing:    31   79  22.5     76     226
Waiting:       14   46  18.1     43     197
Total:         46  224 434.2    105    5162

Percentage of the requests served within a certain time (ms)
  50%    105
  66%    118
  75%    131
  80%    139
  90%    177
  95%   1120
  98%   1160
  99%   2149
 100%   5162 (longest request)
```

```bash
❯  for i in {1..16}; do ( count=$(gtimeout 30 curl -s -N -H "Accept: text/event-stream" http://192.168.4.1/events 2>&1 | grep -c "^data:"); echo "Total: $count events, $(echo "$count / 4" | bc -l) events / second" ) & done;
Total: 1284 events, 321.00000000000000000000 events / second
Total: 1398 events, 349.50000000000000000000 events / second
Total: 1398 events, 349.50000000000000000000 events / second
Total: 1311 events, 327.75000000000000000000 events / second
Total: 1398 events, 349.50000000000000000000 events / second
Total: 1481 events, 370.25000000000000000000 events / second
Total: 1481 events, 370.25000000000000000000 events / second
Total: 1334 events, 333.50000000000000000000 events / second
Total: 1334 events, 333.50000000000000000000 events / second
Total: 1329 events, 332.25000000000000000000 events / second
Total: 1334 events, 333.50000000000000000000 events / second
Total: 1481 events, 370.25000000000000000000 events / second
Total: 1399 events, 349.75000000000000000000 events / second
Total: 1333 events, 333.25000000000000000000 events / second
Total: 1398 events, 349.50000000000000000000 events / second
Total: 1481 events, 370.25000000000000000000 events / second
```

```
ServerSentEvents.ino => OK
```

```
WebSocket.ino => OK
```

```
Templates.ino => OK

❯  curl --output - http://192.168.4.1/dynamic.html | hexdump 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    77    0    77    0     0   2287      0 --:--:-- --:--:-- --:--:--  2333
0000000 3c00 4421 434f 5954 4550 6820 6d74 3e6c
0000010 3c0a 7468 6c6d 0a3e 623c 646f 3e79 200a
0000020 2020 3c20 3168 483e 6c65 6f6c 202c 6f42
0000030 2062 3534 3434 3c32 682f 3e31 3c0a 622f
0000040 646f 3e79 3c0a 682f 6d74 3e6c 000a     
000004d
```

I have also tried other endpoints and I am not able to reproduce @yoursunny issue.

To me the PR is good to go.

**Also. no memory leak. I have monitored the heap.**

**Review by mathieucarbou — APPROVED** [review]

**Review by mathieucarbou — APPROVED** [review]

**Comment by yoursunny** [comment]
I think it's OK now, for commit bb0dd468860cdc3ef59781ed8469ee252149edce:

✅ **Templates.ino**
✅ **ChunkResponse.ino**
✅ #315 MRE

**Comment by vortigont** [comment]
ah! that `sprintf` :) Should've used `snprintf` probably, but your solution is pretty interesting per ce, @mathieucarbou  :)
OK, I think we are good to go finally 👍
